define({
    "_widgetLabel": "Generar vectores de movimiento",
    "capa": "Seleccionar capa con localizaciones históricas",
    "tooltipSobreCapa":"Clic derecho para ver las opciones de la capa",
    "tituloCapas": "Capas de vectores generadas",
    "ejecutar": "Generar vectores",
    "nombreCapaGenerada": "Vectores de ",    
    "nombreCapaGeneradaSoloUna": "Localización de ",
    "eliminarCapas": "Eliminar capas",
    "tituloAlerta": "¡Precaución!",
    "contenidoAlerta": "¿Confirma el borrado de la capa? Esta acción es irreversible",
    "alertaOK": "Si",
    "alertaCancel": "No",
    "capaCero": "Seleccione un capa",
    "menuContextEliminarCapa": "Quitar capa",
    "menuContextZoomCapa": "Zoom a los vectores",
    "menuContextAnimacion": "Activar animación",
    "menuContextDesAnimacion": "Desactivar animación",
    "menuContextSimbologia": "Simbología",
    "menuContextTexto": "Textos",
    "menuContextTextoColor": "Color del texto",
    "menuContextLineas": "Vectores",
    "menuContextLineasGrosor": "Grosor de línea",
    "menuContextLineasColor": "Color de línea",
    "menuContextTextoTamanio": "Tamaño del texto",
    "menuContextLineasTipo": "Estilo de línea",
    "menuContextualTLSolid": "Línea sólida",
    "menuContextualTLShort":"Trazos cortos",
    "menuContextualTLLong": "Trazos largos",
    "menuContextualTLShortDot": "Trazo con punto",
    "menuContextualTLLongDot": "Trazo largo con punto",
    "menuContextualTLDot": "Puntos",
    "infoTemplTitulo": "Vectores del numeral",
    "infoTemplOrg": "Seguimiento de",
    "infoTemplFechaIni": "Fecha posición inicial",
    "InfoTemplFechaFin": "Fecha posición final",
    "InfoTemplVelocidad": "Velocidad teórica",
    "InfoTemplnudos": "nudos",
    "InfoTemplTiempo": "Tiempo transcurrido entre posiciones",
    "InfoTemplDistancia": "Distancia teórica"
});