define({
  root: ({
    _widgetLabel: "Generate motion vector",
    capa: "Select layer with historical locations",
    tooltipSobreCapa:"Right click to see layer options",
    tituloCapas: "Generated vector layers",
    ejecutar: "Generate vectors",
    nombreCapaGenerada: "Vectors of ",
    nombreCapaGeneradaSoloUna: "Location of ",
    eliminarCapas: "Remove layers",
    tituloAlerta: "Warning!",
    contenidoAlerta: "Do you confirm the layer removal?. This action is not reversible.",
    alertaOK: "Yes",
    alertaCancel: "No",
    capaCero: "Select a layer",
    menuContextEliminarCapa: "Remove layer",
    menuContextZoomCapa: "Zoom to vectors",
    menuContextAnimacion: "Activate animation",
    menuContextDesAnimacion: "Deactivate animación",
    menuContextSimbologia: "Simbology",
    menuContextTexto: "Texts",
    menuContextTextoColor: "Text color",
    menuContextLineas: "Vectors",
    menuContextLineasGrosor: "Line width",
    menuContextLineasColor: "Line color",
    menuContextTextoTamanio: "Text size",
		menuContextLineasTipo: "Line style",
		menuContextualTLSolid: "Solid line",
		menuContextualTLShort:"Short dash",
		menuContextualTLLong: "Long dash",
		menuContextualTLShortDot: "Short dash dot",
		menuContextualTLLongDot: "Long dash dot",
		menuContextualTLDot: "Dots line",
    infoTemplTitulo: "Data of",
    infoTemplOrg: "Track of ",
    infoTemplFechaIni: "Initial position date",
    InfoTemplFechaFin: "Final position date",
    InfoTemplVelocidad: "Theoretical speed",
    InfoTemplnudos: "knots",
    InfoTemplTiempo: "Time elapsed",
    InfoTemplDistancia: "Theoretical distance"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 1,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});